print("Anti-Gravity Adventure")
print("Level one")
print("You wake up stranded on a ship.")
name = input("Your name is: ")
print(name,"wakes up in an unknown spaceship. A mysterious artifact lies on the ground.")
print("Does",name,"...")
print("A. Examine the artifact")
print("B. Try to find an exit")
answer1 = input("Answer:")

